
Vagrant.configure("2") do |config|

config.vm.box = "sbeliakou/centos"

 	config.vm.define :zabbix do |zabbix|
	zabbix.vm.hostname = "srv"
	zabbix.vm.network "private_network", ip: "192.168.56.240"
	zabbix.vm.provision :shell, :path=> "zabbix_srv.sh"
	zabbix.vm.provider "virtualbox" do |vb|
   	 vb.name="Zabbix_Srv"
  	 vb.memory = "2048"
      	end

 end	
	config.vm.define :zabbix1 do |zabbix1|
	zabbix1.vm.hostname = "agent"
	zabbix1.vm.network "private_network", ip: "192.168.56.241"
	zabbix1.vm.provision :shell, :path=> "zabbix_agent.sh"
	zabbix1.vm.provider "virtualbox" do |vb|
   	 vb.name="Zabbix_agent"
   	 vb.memory = "2048"
      	end
 end
end
